/* Stub table for the "vector" module.
   This file must be included in the stub shared library. */

/** ------------------------------------------------------------ 
 ** Stub table for the "vector" module.
 ** --------------------------------------------------------- */

/* Functions stub table for the "vector" module. */

const ucl_vector_stub_table_t ucl_vector_stub_table = {
  ucl_vector_initialise,
  ucl_vector_initialise_size,
  ucl_vector_initialise_pad,
  ucl_vector_initialise_step_up,
  ucl_vector_initialise_step_down,
  ucl_vector_constructor,
  ucl_vector_destructor,
  ucl_vector_number_of_step_up_slots,
  ucl_vector_number_of_step_down_slots,
  ucl_vector_number_of_padding_slots,
  ucl_vector_index_to_slot,
  ucl_vector_index_to_new_slot,
  ucl_vector_last_index,
  ucl_vector_slot_to_index,
  ucl_vector_pointer_is_valid_slot,
  ucl_vector_index_is_valid,
  ucl_vector_range_is_valid,
  ucl_vector_insert,
  ucl_vector_insert_sort,
  ucl_vector_erase,
  ucl_vector_slot_dimension,
  ucl_vector_size,
  ucl_vector_set_compar,
  ucl_vector_get_memory_block,
  ucl_vector_get_data_block,
  ucl_vector_quick_sort,
  ucl_vector_iterator_forward,
  ucl_vector_iterator_backward,
  ucl_vector_enlarge,
  ucl_vector_restrict,
  ucl_vector_set_memory_to_zero,
  ucl_vector_number_of_free_slots,
  ucl_vector_find,
  ucl_vector_sort_find,
  ucl_vector_binary_search,
  ucl_vector_append_range,
  ucl_vector_append,
  ucl_vector_append_more,
  ucl_vector_insert_vector,
  ucl_vector_erase_range,
  ucl_vector_compare_range,
  ucl_vector_compare,
  ucl_vector_equal,
  ucl_vector_mark_all_slots_as_used,
  ucl_vector_enlarge_for_slots,
  ucl_vector_append_block,
  ucl_vector_initialise_buffer,
  ucl_vector_swallow_block,
  ucl_vector_running,
  ucl_vector_push_back,
  ucl_vector_push_front,
  ucl_vector_pop_back,
  ucl_vector_pop_front,
  ucl_vector_reset,
  ucl_vector_clean,
  ucl_vector_register_allocator,
  ucl_vector_sorted,
  ucl_vector_block_from_range,
  ucl_vector_range_from_block,
  ucl_vector_get_free_block_at_end,
  ucl_vector_get_free_block_at_beginning,
  ucl_vector_mark_as_used,
  ucl_vector_update_number_of_step_up_slots,
  ucl_vector_update_number_of_step_down_slots,
  ucl_vector_update_number_of_padding_slots,
  ucl_vector_for_each,
  ucl_vector_for_each_multiple_from_array,
  ucl_vector_for_each_multiple,
  ucl_vector_map,
  ucl_vector_for_each_in_range,
  ucl_vector_map_range,
  ucl_vector_iterator_range_forward,
  ucl_vector_iterator_range_backward,
  ucl_vector_map_multiple_from_array,
  ucl_vector_map_multiple,
  ucl_vector_range,
  ucl_vector_range_from_position_to_end,
  ucl_vector_range_from_end_to_position,
  ucl_vector_range_from_end_with_span,
  ucl_vector_enlarge_for_range,
  ucl_vector_append_more_from_array,
  ucl_vector_insert_range,
  ucl_vector_insert_block,
  ucl_vector_copy_range,
  ucl_vector_set_block,
  ucl_vector_get_block,
  ucl_vector_index_is_valid_new,
  ucl_vector_will_enlarge,
  ucl_vector_will_restrict,
  ucl_vector_enlarged_size,
  ucl_vector_restricted_size,
  ucl_vector_mark_allocated_range_as_used
};


/* end of section */
